### ISSUE TITLE
Look into using a templating library for Cloud Formation

### ISSUE THREAD

**Issue by rossf7** [giantswarm/aws-operator#375] opened 2017-08-15 07:22 UTC
Currently, the Cloud Formation template for the ASG stack is a plain Go template. Using https://github.com/crewjam/go-cloudformation might make it easier to generate templates and provide better type safety.

But this involves integrating another library and it depends on how much we use Cloud Formation in the operator.

**Comment by rossf7** [comment] 2017-08-15 12:26
Feedback from @kopiczko on crewjam/go-cloudformation https://github.com/giantswarm/aws-operator/pull/374#issuecomment-322436842

**Comment by xh3b4sd** [comment] 2017-09-27 09:25
@teemow this is what you are currently working on AFAIK. Can we link and close this issue to your actual one?

**Comment by xh3b4sd** [comment] 2017-10-02 13:11
Duplicate of https://github.com/giantswarm/giantswarm/issues/1850.

**Closed by xh3b4sd** 2017-10-02 13:11 UTC
